site_name: The Shattered Pale
site_description: Tabletop RPG Setting & Compendium for Raasha
docs_dir: content/setting
site_dir: public

theme:
  name: material
  palette:
    - scheme: slate
      primary: teal
      accent: amber
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    - scheme: default
      primary: teal
      accent: amber
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
plugins:
  - search
  - tags

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - tables
  - attr_list
  - def_list
  - toc:
      permalink: true

extra:
  social:
    - icon: fontawesome/solid/store
      link: https://theshatteredpale.com
      name: Official Storefront

nav:
  - Overview: index.md
  - History & Myth:
      - Age of Cosmos: history/world-notes.md
      - The Arrival: history/the-arrival.md
      - The War for Raasha: history/the-war-for-raasha.md
  - Species:
      - Aasimar: species/aasimar.md
      - Dragonborn: species/dragonborn.md
      - Dwarf: species/dwarf.md
      - Elf: species/elf.md
      - Genasi: species/genasi.md
      - Goliath: species/goliath.md
      - Human: species/human.md
      - Orc: species/orc.md
      - Saurian: species/saurian.md
      - Tiefling: species/tiefling.md
  - Pantheons:
      - Aestios: pantheons/aestios.md
      - Anazuatl: pantheons/anazuatl.md
      - Dwasti: pantheons/dwasti.md
      - Ziratu: pantheons/ziratu.md
  - Geography:
      - Ardona: geography/ardona.md
      - Khor: geography/khor.md
      - Sa Zortao: geography/sa-zortao.md
      - Soland: geography/soland.md
      - Tsugash: geography/tsugash.md
  - Factions:
      - Endaros: factions/endaros.md

